title: Site

sections:
  pages:
    type: pages

  fields:
    type: fields
    fields:
      lineA:
        type: line
      texts:
        type: structure
        label: Textes
        columns:
          text:
            width: 3/4
          size:
            width: 1/8
            after: rem
          color:
            width: 1/8
          overflow:
            width: 1/12
        fields:
          text:
            type: textarea
            size: large
            buttons: false
            required: true
          size:
            type: number
            after: rem
            step: 0.01
            max: 100
            min: 0.01
            width: 1/2
            required: true
            default: 1
            help: 1rem = 15px
          color:
            type: colors
            width: 1/2
            required: true
          overflow:
            type: toggles
            options:
              - scroll
              - wrap
      lineB:
        type: line
      fonts:
        type: structure
        columns:
          name:
            width: 1/6
          file:
            width: 2/6
          stylesets:
            width: 3/6
        fields:
          name:
            type: text
          file:
            type: files
            multiple: false
            uploads:
              template: upload-font
          stylesets:
            type: multiselect
            options:
              - ss01
              - ss02
              - ss03
              - ss04
              - ss05
              - ss06
              - ss07
              - ss08
              - ss09
              - ss10
